/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'WinCIS.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct HINSTANCE__;
struct HKEY__;
struct _RTL_CRITICAL_SECTION_DEBUG;
struct tagVARIANT;
struct IUnknown;
struct IUnknownVtbl;
struct _GUID;
struct IDispatch;
struct IDispatchVtbl;
struct ITypeInfo;
struct ITypeInfoVtbl;
struct tagTYPEATTR;
struct tagTYPEDESC;
struct tagARRAYDESC;
struct ITypeComp;
struct ITypeCompVtbl;
union tagBINDPTR;
struct tagFUNCDESC;
struct tagELEMDESC;
struct tagPARAMDESCEX;
struct tagVARDESC;
struct tagDISPPARAMS;
struct tagEXCEPINFO;
struct ITypeLib;
struct ITypeLibVtbl;
struct tagTLIBATTR;
struct tagSAFEARRAY;
struct tagDEC;
struct IRecordInfo;
struct IRecordInfoVtbl;
struct _s_ThrowInfo;
struct _s_CatchableTypeArray;
struct _s_CatchableType;
struct TypeDescriptor;
struct _IP_ADAPTER_ADDRESSES_LH;
struct _IP_ADAPTER_UNICAST_ADDRESS_LH;
struct sockaddr;
struct _IP_ADAPTER_ANYCAST_ADDRESS_XP;
struct _IP_ADAPTER_MULTICAST_ADDRESS_XP;
struct _IP_ADAPTER_DNS_SERVER_ADDRESS_XP;
struct _IP_ADAPTER_PREFIX_XP;
struct _IP_ADAPTER_WINS_SERVER_ADDRESS_LH;
struct _IP_ADAPTER_GATEWAY_ADDRESS_LH;
struct _IP_ADAPTER_DNS_SUFFIX;
struct _EXCEPTION_RECORD;
struct _CONTEXT;
union _LARGE_INTEGER;
struct _exception;
struct HMENU__;
struct HWND__;

/* 1 */
typedef struct HINSTANCE__ *HINSTANCE;

/* 2 */
struct HINSTANCE__
{
  int unused;
};

/* 4 */
typedef char CHAR;

/* 3 */
typedef CHAR *LPSTR;

/* 5 */
enum __bitmask __TI_flags
{
  TI_IsConst = 0x1,
  TI_IsVolatile = 0x2,
  TI_IsUnaligned = 0x4,
  TI_IsPure = 0x8,
  TI_IsWinRT = 0x10,
};

/* 6 */
enum __bitmask __CT_flags
{
  CT_IsSimpleType = 0x1,
  CT_ByReferenceOnly = 0x2,
  CT_HasVirtualBase = 0x4,
  CT_IsWinRTHandle = 0x8,
  CT_IsStdBadAlloc = 0x10,
};

/* 7 */
struct FuncInfo
{
  unsigned __int32 magicNumber : 29;
  unsigned __int32 bbtFlags : 3;
  int maxState __dec;
  void *pUnwindMap;
  int nTryBlocks __dec;
  void *pTryBlockMap;
  int nIPMapEntries __dec;
  void *pIPtoStateMap;
  void *pESTypeList;
  int EHFlags __hex;
};

/* 8 */
struct UnwindMapEntry
{
  int toState __dec;
  void *action;
};

/* 9 */
struct TryBlockMapEntry
{
  int tryLow __dec;
  int tryHigh __dec;
  int catchHigh __dec;
  int nCatches __dec;
  void *pHandlerArray;
};

/* 10 */
struct HandlerType
{
  int adjectives __hex;
  void *pType;
  int dispCatchObj __dec;
  void *addressOfHandler;
};

/* 11 */
struct _EH4_SCOPETABLE_RECORD
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 13 */
typedef unsigned int DWORD;

/* 12 */
struct _EH4_SCOPETABLE
{
  DWORD GSCookieOffset;
  DWORD GSCookieXOROffset;
  DWORD EHCookieOffset;
  DWORD EHCookieXOROffset;
  struct _EH4_SCOPETABLE_RECORD ScopeRecord[];
};

/* 14 */
typedef void *PVOID;

/* 15 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 16 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 17 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 18 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 19 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 20 */
typedef unsigned int size_t;

/* 21 */
typedef struct HKEY__ *HKEY;

/* 22 */
struct HKEY__
{
  int unused;
};

/* 23 */
typedef void *LPVOID;

/* 24 */
typedef void *HANDLE;

/* 26 */
typedef __int64 __time64_t;

/* 25 */
#pragma pack(push, 8)
struct __timeb64
{
  __time64_t time;
  unsigned __int16 millitm;
  __int16 timezone;
  __int16 dstflag;
};
#pragma pack(pop)

/* 27 */
typedef const CHAR *LPCSTR;

/* 30 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 29 */
typedef struct _FILETIME FILETIME;

/* 28 */
struct _WIN32_FIND_DATAA
{
  DWORD dwFileAttributes;
  FILETIME ftCreationTime;
  FILETIME ftLastAccessTime;
  FILETIME ftLastWriteTime;
  DWORD nFileSizeHigh;
  DWORD nFileSizeLow;
  DWORD dwReserved0;
  DWORD dwReserved1;
  CHAR cFileName[260];
  CHAR cAlternateFileName[14];
};

/* 32 */
typedef unsigned __int16 WORD;

/* 31 */
struct _SYSTEMTIME
{
  WORD wYear;
  WORD wMonth;
  WORD wDayOfWeek;
  WORD wDay;
  WORD wHour;
  WORD wMinute;
  WORD wSecond;
  WORD wMilliseconds;
};

/* 35 */
typedef unsigned __int8 BYTE;

/* 34 */
typedef BYTE *LPBYTE;

/* 33 */
struct _STARTUPINFOA
{
  DWORD cb;
  LPSTR lpReserved;
  LPSTR lpDesktop;
  LPSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};

/* 36 */
struct _PROCESS_INFORMATION
{
  HANDLE hProcess;
  HANDLE hThread;
  DWORD dwProcessId;
  DWORD dwThreadId;
};

/* 38 */
typedef struct _RTL_CRITICAL_SECTION_DEBUG *PRTL_CRITICAL_SECTION_DEBUG;

/* 42 */
typedef int LONG;

/* 43 */
typedef unsigned int ULONG_PTR;

/* 37 */
#pragma pack(push, 8)
struct _RTL_CRITICAL_SECTION
{
  PRTL_CRITICAL_SECTION_DEBUG DebugInfo;
  LONG LockCount;
  LONG RecursionCount;
  HANDLE OwningThread;
  HANDLE LockSemaphore;
  ULONG_PTR SpinCount;
};
#pragma pack(pop)

/* 41 */
struct _LIST_ENTRY
{
  struct _LIST_ENTRY *Flink;
  struct _LIST_ENTRY *Blink;
};

/* 40 */
typedef struct _LIST_ENTRY LIST_ENTRY;

/* 39 */
struct _RTL_CRITICAL_SECTION_DEBUG
{
  WORD Type;
  WORD CreatorBackTraceIndex;
  struct _RTL_CRITICAL_SECTION *CriticalSection;
  LIST_ENTRY ProcessLocksList;
  DWORD EntryCount;
  DWORD ContentionCount;
  DWORD Flags;
  WORD CreatorBackTraceIndexHigh;
  WORD SpareWORD;
};

/* 45 */
typedef int LONG_PTR;

/* 44 */
typedef LONG_PTR LPARAM;

/* 48 */
typedef unsigned __int16 wchar_t;

/* 47 */
typedef wchar_t WCHAR;

/* 49 */
typedef struct _SYSTEMTIME SYSTEMTIME;

/* 46 */
struct _TIME_ZONE_INFORMATION
{
  LONG Bias;
  WCHAR StandardName[32];
  SYSTEMTIME StandardDate;
  LONG StandardBias;
  WCHAR DaylightName[32];
  SYSTEMTIME DaylightDate;
  LONG DaylightBias;
};

/* 50 */
#pragma pack(push, 8)
struct tm
{
  int tm_sec;
  int tm_min;
  int tm_hour;
  int tm_mday;
  int tm_mon;
  int tm_year;
  int tm_wday;
  int tm_yday;
  int tm_isdst;
};
#pragma pack(pop)

/* 52 */
typedef struct tagVARIANT VARIANT;

/* 51 */
typedef VARIANT VARIANTARG;

/* 56 */
typedef unsigned __int16 VARTYPE;

/* 58 */
typedef __int64 LONGLONG;

/* 59 */
typedef __int16 SHORT;

/* 60 */
typedef float FLOAT;

/* 61 */
typedef double DOUBLE;

/* 62 */
typedef __int16 VARIANT_BOOL;

/* 63 */
typedef LONG SCODE;

/* 67 */
typedef unsigned int ULONG;

/* 66 */
struct tagCY::$3EA7BC8C29B528C7CA1203FC489E132F
{
  ULONG Lo;
  LONG Hi;
};

/* 65 */
union tagCY
{
  struct
  {
    ULONG Lo;
    LONG Hi;
  };
  LONGLONG int64;
};

/* 64 */
typedef union tagCY CY;

/* 68 */
typedef double DATE;

/* 70 */
typedef WCHAR OLECHAR;

/* 69 */
typedef OLECHAR *BSTR;

/* 138 */
typedef struct tagSAFEARRAY SAFEARRAY;

/* 94 */
typedef unsigned __int16 USHORT;

/* 140 */
typedef unsigned __int64 ULONGLONG;

/* 126 */
typedef int INT;

/* 79 */
typedef unsigned int UINT;

/* 141 */
typedef struct tagDEC DECIMAL;

/* 147 */
#pragma pack(push, 8)
struct tagVARIANT::$::$::$E09503A454170B491AC1C4312CE36FE6::$0FDBD249F1AECD6A49409B6B82281578
{
  PVOID pvRecord;
  IRecordInfo *pRecInfo;
};
#pragma pack(pop)

/* 57 */
#pragma pack(push, 8)
union tagVARIANT::$::$65D68C826D16CA47CF95571D7BFCD657::$E09503A454170B491AC1C4312CE36FE6
{
  LONGLONG llVal;
  LONG lVal;
  BYTE bVal;
  SHORT iVal;
  FLOAT fltVal;
  DOUBLE dblVal;
  VARIANT_BOOL boolVal;
  SCODE scode;
  CY cyVal;
  DATE date;
  BSTR bstrVal;
  IUnknown *punkVal;
  IDispatch *pdispVal;
  SAFEARRAY *parray;
  BYTE *pbVal;
  SHORT *piVal;
  LONG *plVal;
  LONGLONG *pllVal;
  FLOAT *pfltVal;
  DOUBLE *pdblVal;
  VARIANT_BOOL *pboolVal;
  SCODE *pscode;
  CY *pcyVal;
  DATE *pdate;
  BSTR *pbstrVal;
  IUnknown **ppunkVal;
  IDispatch **ppdispVal;
  SAFEARRAY **pparray;
  VARIANT *pvarVal;
  PVOID byref;
  CHAR cVal;
  USHORT uiVal;
  ULONG ulVal;
  ULONGLONG ullVal;
  INT intVal;
  UINT uintVal;
  DECIMAL *pdecVal;
  CHAR *pcVal;
  USHORT *puiVal;
  ULONG *pulVal;
  ULONGLONG *pullVal;
  INT *pintVal;
  UINT *puintVal;
  #pragma pack(push, 8)
  struct
  {
    PVOID pvRecord;
    IRecordInfo *pRecInfo;
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 55 */
#pragma pack(push, 8)
struct tagVARIANT::$E93DC971A089CC95F6C875332324C1E7::$65D68C826D16CA47CF95571D7BFCD657
{
  VARTYPE vt;
  WORD wReserved1;
  WORD wReserved2;
  WORD wReserved3;
  #pragma pack(push, 8)
  union
  {
    LONGLONG llVal;
    LONG lVal;
    BYTE bVal;
    SHORT iVal;
    FLOAT fltVal;
    DOUBLE dblVal;
    VARIANT_BOOL boolVal;
    SCODE scode;
    CY cyVal;
    DATE date;
    BSTR bstrVal;
    IUnknown *punkVal;
    IDispatch *pdispVal;
    SAFEARRAY *parray;
    BYTE *pbVal;
    SHORT *piVal;
    LONG *plVal;
    LONGLONG *pllVal;
    FLOAT *pfltVal;
    DOUBLE *pdblVal;
    VARIANT_BOOL *pboolVal;
    SCODE *pscode;
    CY *pcyVal;
    DATE *pdate;
    BSTR *pbstrVal;
    IUnknown **ppunkVal;
    IDispatch **ppdispVal;
    SAFEARRAY **pparray;
    VARIANT *pvarVal;
    PVOID byref;
    CHAR cVal;
    USHORT uiVal;
    ULONG ulVal;
    ULONGLONG ullVal;
    INT intVal;
    UINT uintVal;
    DECIMAL *pdecVal;
    CHAR *pcVal;
    USHORT *puiVal;
    ULONG *pulVal;
    ULONGLONG *pullVal;
    INT *pintVal;
    UINT *puintVal;
    #pragma pack(push, 8)
    struct
    {
      PVOID pvRecord;
      IRecordInfo *pRecInfo;
    };
    #pragma pack(pop)
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 144 */
struct tagDEC::$64EC678C49E7BE49873AFBFB7A849D34::$7F8459940C2B08BD5D82B0F27239141B
{
  BYTE scale;
  BYTE sign;
};

/* 143 */
union tagDEC::$64EC678C49E7BE49873AFBFB7A849D34
{
  struct
  {
    BYTE scale;
    BYTE sign;
  };
  USHORT signscale;
};

/* 146 */
struct tagDEC::$D28E26DEC3EC762C06C2AA9D0F7AC301::$674876891A86A76F12C10005982BCA56
{
  ULONG Lo32;
  ULONG Mid32;
};

/* 145 */
union tagDEC::$D28E26DEC3EC762C06C2AA9D0F7AC301
{
  struct
  {
    ULONG Lo32;
    ULONG Mid32;
  };
  ULONGLONG Lo64;
};

/* 142 */
struct tagDEC
{
  USHORT wReserved;
  union
  {
    struct
    {
      BYTE scale;
      BYTE sign;
    };
    USHORT signscale;
  };
  ULONG Hi32;
  union
  {
    struct
    {
      ULONG Lo32;
      ULONG Mid32;
    };
    ULONGLONG Lo64;
  };
};

/* 54 */
#pragma pack(push, 8)
union tagVARIANT::$E93DC971A089CC95F6C875332324C1E7
{
  #pragma pack(push, 8)
  struct
  {
    VARTYPE vt;
    WORD wReserved1;
    WORD wReserved2;
    WORD wReserved3;
    #pragma pack(push, 8)
    union
    {
      LONGLONG llVal;
      LONG lVal;
      BYTE bVal;
      SHORT iVal;
      FLOAT fltVal;
      DOUBLE dblVal;
      VARIANT_BOOL boolVal;
      SCODE scode;
      CY cyVal;
      DATE date;
      BSTR bstrVal;
      IUnknown *punkVal;
      IDispatch *pdispVal;
      SAFEARRAY *parray;
      BYTE *pbVal;
      SHORT *piVal;
      LONG *plVal;
      LONGLONG *pllVal;
      FLOAT *pfltVal;
      DOUBLE *pdblVal;
      VARIANT_BOOL *pboolVal;
      SCODE *pscode;
      CY *pcyVal;
      DATE *pdate;
      BSTR *pbstrVal;
      IUnknown **ppunkVal;
      IDispatch **ppdispVal;
      SAFEARRAY **pparray;
      VARIANT *pvarVal;
      PVOID byref;
      CHAR cVal;
      USHORT uiVal;
      ULONG ulVal;
      ULONGLONG ullVal;
      INT intVal;
      UINT uintVal;
      DECIMAL *pdecVal;
      CHAR *pcVal;
      USHORT *puiVal;
      ULONG *pulVal;
      ULONGLONG *pullVal;
      INT *pintVal;
      UINT *puintVal;
      #pragma pack(push, 8)
      struct
      {
        PVOID pvRecord;
        IRecordInfo *pRecInfo;
      };
      #pragma pack(pop)
    };
    #pragma pack(pop)
  };
  #pragma pack(pop)
  DECIMAL decVal;
};
#pragma pack(pop)

/* 53 */
#pragma pack(push, 8)
struct tagVARIANT
{
  #pragma pack(push, 8)
  union
  {
    #pragma pack(push, 8)
    struct
    {
      VARTYPE vt;
      WORD wReserved1;
      WORD wReserved2;
      WORD wReserved3;
      #pragma pack(push, 8)
      union
      {
        LONGLONG llVal;
        LONG lVal;
        BYTE bVal;
        SHORT iVal;
        FLOAT fltVal;
        DOUBLE dblVal;
        VARIANT_BOOL boolVal;
        SCODE scode;
        CY cyVal;
        DATE date;
        BSTR bstrVal;
        IUnknown *punkVal;
        IDispatch *pdispVal;
        SAFEARRAY *parray;
        BYTE *pbVal;
        SHORT *piVal;
        LONG *plVal;
        LONGLONG *pllVal;
        FLOAT *pfltVal;
        DOUBLE *pdblVal;
        VARIANT_BOOL *pboolVal;
        SCODE *pscode;
        CY *pcyVal;
        DATE *pdate;
        BSTR *pbstrVal;
        IUnknown **ppunkVal;
        IDispatch **ppdispVal;
        SAFEARRAY **pparray;
        VARIANT *pvarVal;
        PVOID byref;
        CHAR cVal;
        USHORT uiVal;
        ULONG ulVal;
        ULONGLONG ullVal;
        INT intVal;
        UINT uintVal;
        DECIMAL *pdecVal;
        CHAR *pcVal;
        USHORT *puiVal;
        ULONG *pulVal;
        ULONGLONG *pullVal;
        INT *pintVal;
        UINT *puintVal;
        #pragma pack(push, 8)
        struct
        {
          PVOID pvRecord;
          IRecordInfo *pRecInfo;
        };
        #pragma pack(pop)
      };
      #pragma pack(pop)
    };
    #pragma pack(pop)
    DECIMAL decVal;
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 71 */
#pragma pack(push, 8)
struct IUnknown
{
  struct IUnknownVtbl *lpVtbl;
};
#pragma pack(pop)

/* 77 */
#pragma pack(push, 8)
struct IDispatch
{
  struct IDispatchVtbl *lpVtbl;
};
#pragma pack(pop)

/* 96 */
#pragma pack(push, 8)
struct tagSAFEARRAYBOUND
{
  ULONG cElements;
  LONG lLbound;
};
#pragma pack(pop)

/* 95 */
typedef struct tagSAFEARRAYBOUND SAFEARRAYBOUND;

/* 139 */
#pragma pack(push, 8)
struct tagSAFEARRAY
{
  USHORT cDims;
  USHORT fFeatures;
  ULONG cbElements;
  ULONG cLocks;
  PVOID pvData;
  SAFEARRAYBOUND rgsabound[1];
};
#pragma pack(pop)

/* 148 */
#pragma pack(push, 8)
struct IRecordInfo
{
  struct IRecordInfoVtbl *lpVtbl;
};
#pragma pack(pop)

/* 76 */
typedef int HRESULT;

/* 74 */
typedef struct _GUID GUID;

/* 73 */
typedef GUID IID;

/* 72 */
#pragma pack(push, 8)
struct IUnknownVtbl
{
  HRESULT (__stdcall *QueryInterface)(IUnknown *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(IUnknown *This);
  ULONG (__stdcall *Release)(IUnknown *This);
};
#pragma pack(pop)

/* 80 */
typedef DWORD LCID;

/* 87 */
typedef OLECHAR *LPOLESTR;

/* 86 */
typedef LONG DISPID;

/* 127 */
typedef struct tagDISPPARAMS DISPPARAMS;

/* 129 */
typedef struct tagEXCEPINFO EXCEPINFO;

/* 78 */
#pragma pack(push, 8)
struct IDispatchVtbl
{
  HRESULT (__stdcall *QueryInterface)(IDispatch *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(IDispatch *This);
  ULONG (__stdcall *Release)(IDispatch *This);
  HRESULT (__stdcall *GetTypeInfoCount)(IDispatch *This, UINT *pctinfo);
  HRESULT (__stdcall *GetTypeInfo)(IDispatch *This, UINT iTInfo, LCID lcid, ITypeInfo **ppTInfo);
  HRESULT (__stdcall *GetIDsOfNames)(IDispatch *This, const IID *const riid, LPOLESTR *rgszNames, UINT cNames, LCID lcid, DISPID *rgDispId);
  HRESULT (__stdcall *Invoke)(IDispatch *This, DISPID dispIdMember, const IID *const riid, LCID lcid, WORD wFlags, DISPPARAMS *pDispParams, VARIANT *pVarResult, EXCEPINFO *pExcepInfo, UINT *puArgErr);
};
#pragma pack(pop)

/* 150 */
typedef const OLECHAR *LPCOLESTR;

/* 137 */
typedef int BOOL;

/* 149 */
#pragma pack(push, 8)
struct IRecordInfoVtbl
{
  HRESULT (__stdcall *QueryInterface)(IRecordInfo *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(IRecordInfo *This);
  ULONG (__stdcall *Release)(IRecordInfo *This);
  HRESULT (__stdcall *RecordInit)(IRecordInfo *This, PVOID pvNew);
  HRESULT (__stdcall *RecordClear)(IRecordInfo *This, PVOID pvExisting);
  HRESULT (__stdcall *RecordCopy)(IRecordInfo *This, PVOID pvExisting, PVOID pvNew);
  HRESULT (__stdcall *GetGuid)(IRecordInfo *This, GUID *pguid);
  HRESULT (__stdcall *GetName)(IRecordInfo *This, BSTR *pbstrName);
  HRESULT (__stdcall *GetSize)(IRecordInfo *This, ULONG *pcbSize);
  HRESULT (__stdcall *GetTypeInfo)(IRecordInfo *This, ITypeInfo **ppTypeInfo);
  HRESULT (__stdcall *GetField)(IRecordInfo *This, PVOID pvData, LPCOLESTR szFieldName, VARIANT *pvarField);
  HRESULT (__stdcall *GetFieldNoCopy)(IRecordInfo *This, PVOID pvData, LPCOLESTR szFieldName, VARIANT *pvarField, PVOID *ppvDataCArray);
  HRESULT (__stdcall *PutField)(IRecordInfo *This, ULONG wFlags, PVOID pvData, LPCOLESTR szFieldName, VARIANT *pvarField);
  HRESULT (__stdcall *PutFieldNoCopy)(IRecordInfo *This, ULONG wFlags, PVOID pvData, LPCOLESTR szFieldName, VARIANT *pvarField);
  HRESULT (__stdcall *GetFieldNames)(IRecordInfo *This, ULONG *pcNames, BSTR *rgBstrNames);
  BOOL (__stdcall *IsMatchingType)(IRecordInfo *This, IRecordInfo *pRecordInfo);
  PVOID (__stdcall *RecordCreate)(IRecordInfo *This);
  HRESULT (__stdcall *RecordCreateCopy)(IRecordInfo *This, PVOID pvSource, PVOID *ppvDest);
  HRESULT (__stdcall *RecordDestroy)(IRecordInfo *This, PVOID pvRecord);
};
#pragma pack(pop)

/* 75 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 81 */
#pragma pack(push, 8)
struct ITypeInfo
{
  struct ITypeInfoVtbl *lpVtbl;
};
#pragma pack(pop)

/* 128 */
#pragma pack(push, 8)
struct tagDISPPARAMS
{
  VARIANTARG *rgvarg;
  DISPID *rgdispidNamedArgs;
  UINT cArgs;
  UINT cNamedArgs;
};
#pragma pack(pop)

/* 130 */
#pragma pack(push, 8)
struct tagEXCEPINFO
{
  WORD wCode;
  WORD wReserved;
  BSTR bstrSource;
  BSTR bstrDescription;
  BSTR bstrHelpFile;
  DWORD dwHelpContext;
  PVOID pvReserved;
  HRESULT (__stdcall *pfnDeferredFillIn)(struct tagEXCEPINFO *);
  SCODE scode;
};
#pragma pack(pop)

/* 83 */
typedef struct tagTYPEATTR TYPEATTR;

/* 106 */
typedef struct tagFUNCDESC FUNCDESC;

/* 121 */
typedef struct tagVARDESC VARDESC;

/* 85 */
typedef DISPID MEMBERID;

/* 97 */
typedef DWORD HREFTYPE;

/* 118 */
enum __bitmask tagINVOKEKIND
{
  INVOKE_FUNC = 0x1,
  INVOKE_PROPERTYGET = 0x2,
  INVOKE_PROPERTYPUT = 0x4,
  INVOKE_PROPERTYPUTREF = 0x8,
};

/* 117 */
typedef enum tagINVOKEKIND INVOKEKIND;

/* 82 */
#pragma pack(push, 8)
struct ITypeInfoVtbl
{
  HRESULT (__stdcall *QueryInterface)(ITypeInfo *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(ITypeInfo *This);
  ULONG (__stdcall *Release)(ITypeInfo *This);
  HRESULT (__stdcall *GetTypeAttr)(ITypeInfo *This, TYPEATTR **ppTypeAttr);
  HRESULT (__stdcall *GetTypeComp)(ITypeInfo *This, ITypeComp **ppTComp);
  HRESULT (__stdcall *GetFuncDesc)(ITypeInfo *This, UINT index, FUNCDESC **ppFuncDesc);
  HRESULT (__stdcall *GetVarDesc)(ITypeInfo *This, UINT index, VARDESC **ppVarDesc);
  HRESULT (__stdcall *GetNames)(ITypeInfo *This, MEMBERID memid, BSTR *rgBstrNames, UINT cMaxNames, UINT *pcNames);
  HRESULT (__stdcall *GetRefTypeOfImplType)(ITypeInfo *This, UINT index, HREFTYPE *pRefType);
  HRESULT (__stdcall *GetImplTypeFlags)(ITypeInfo *This, UINT index, INT *pImplTypeFlags);
  HRESULT (__stdcall *GetIDsOfNames)(ITypeInfo *This, LPOLESTR *rgszNames, UINT cNames, MEMBERID *pMemId);
  HRESULT (__stdcall *Invoke)(ITypeInfo *This, PVOID pvInstance, MEMBERID memid, WORD wFlags, DISPPARAMS *pDispParams, VARIANT *pVarResult, EXCEPINFO *pExcepInfo, UINT *puArgErr);
  HRESULT (__stdcall *GetDocumentation)(ITypeInfo *This, MEMBERID memid, BSTR *pBstrName, BSTR *pBstrDocString, DWORD *pdwHelpContext, BSTR *pBstrHelpFile);
  HRESULT (__stdcall *GetDllEntry)(ITypeInfo *This, MEMBERID memid, INVOKEKIND invKind, BSTR *pBstrDllName, BSTR *pBstrName, WORD *pwOrdinal);
  HRESULT (__stdcall *GetRefTypeInfo)(ITypeInfo *This, HREFTYPE hRefType, ITypeInfo **ppTInfo);
  HRESULT (__stdcall *AddressOfMember)(ITypeInfo *This, MEMBERID memid, INVOKEKIND invKind, PVOID *ppv);
  HRESULT (__stdcall *CreateInstance)(ITypeInfo *This, IUnknown *pUnkOuter, const IID *const riid, PVOID *ppvObj);
  HRESULT (__stdcall *GetMops)(ITypeInfo *This, MEMBERID memid, BSTR *pBstrMops);
  HRESULT (__stdcall *GetContainingTypeLib)(ITypeInfo *This, ITypeLib **ppTLib, UINT *pIndex);
  void (__stdcall *ReleaseTypeAttr)(ITypeInfo *This, TYPEATTR *pTypeAttr);
  void (__stdcall *ReleaseFuncDesc)(ITypeInfo *This, FUNCDESC *pFuncDesc);
  void (__stdcall *ReleaseVarDesc)(ITypeInfo *This, VARDESC *pVarDesc);
};
#pragma pack(pop)

/* 89 */
enum tagTYPEKIND
{
  TKIND_ENUM = 0x0,
  TKIND_RECORD = 0x1,
  TKIND_MODULE = 0x2,
  TKIND_INTERFACE = 0x3,
  TKIND_DISPATCH = 0x4,
  TKIND_COCLASS = 0x5,
  TKIND_ALIAS = 0x6,
  TKIND_UNION = 0x7,
  TKIND_MAX = 0x8,
};

/* 88 */
typedef enum tagTYPEKIND TYPEKIND;

/* 92 */
#pragma pack(push, 8)
union tagTYPEDESC::$AC700B6542D8071E244CADABF8A32897
{
  struct tagTYPEDESC *lptdesc;
  struct tagARRAYDESC *lpadesc;
  HREFTYPE hreftype;
};
#pragma pack(pop)

/* 91 */
#pragma pack(push, 8)
struct tagTYPEDESC
{
  #pragma pack(push, 8)
  union
  {
    struct tagTYPEDESC *lptdesc;
    struct tagARRAYDESC *lpadesc;
    HREFTYPE hreftype;
  };
  #pragma pack(pop)
  VARTYPE vt;
};
#pragma pack(pop)

/* 90 */
typedef struct tagTYPEDESC TYPEDESC;

/* 99 */
#pragma pack(push, 8)
struct tagIDLDESC
{
  ULONG_PTR dwReserved;
  USHORT wIDLFlags;
};
#pragma pack(pop)

/* 98 */
typedef struct tagIDLDESC IDLDESC;

/* 84 */
#pragma pack(push, 8)
struct tagTYPEATTR
{
  GUID guid;
  LCID lcid;
  DWORD dwReserved;
  MEMBERID memidConstructor;
  MEMBERID memidDestructor;
  LPOLESTR lpstrSchema;
  ULONG cbSizeInstance;
  TYPEKIND typekind;
  WORD cFuncs;
  WORD cVars;
  WORD cImplTypes;
  WORD cbSizeVft;
  WORD cbAlignment;
  WORD wTypeFlags;
  WORD wMajorVerNum;
  WORD wMinorVerNum;
  TYPEDESC tdescAlias;
  IDLDESC idldescType;
};
#pragma pack(pop)

/* 100 */
#pragma pack(push, 8)
struct ITypeComp
{
  struct ITypeCompVtbl *lpVtbl;
};
#pragma pack(pop)

/* 108 */
typedef struct tagELEMDESC ELEMDESC;

/* 116 */
enum tagFUNCKIND
{
  FUNC_VIRTUAL = 0x0,
  FUNC_PUREVIRTUAL = 0x1,
  FUNC_NONVIRTUAL = 0x2,
  FUNC_STATIC = 0x3,
  FUNC_DISPATCH = 0x4,
};

/* 115 */
typedef enum tagFUNCKIND FUNCKIND;

/* 120 */
enum tagCALLCONV
{
  CC_FASTCALL = 0x0,
  CC_CDECL = 0x1,
  CC_MSCPASCAL = 0x2,
  CC_PASCAL = 0x2,
  CC_MACPASCAL = 0x3,
  CC_STDCALL = 0x4,
  CC_FPFASTCALL = 0x5,
  CC_SYSCALL = 0x6,
  CC_MPWCDECL = 0x7,
  CC_MPWPASCAL = 0x8,
  CC_MAX = 0x9,
};

/* 119 */
typedef enum tagCALLCONV CALLCONV;

/* 113 */
typedef struct tagPARAMDESCEX *LPPARAMDESCEX;

/* 112 */
#pragma pack(push, 8)
struct tagPARAMDESC
{
  LPPARAMDESCEX pparamdescex;
  USHORT wParamFlags;
};
#pragma pack(pop)

/* 111 */
typedef struct tagPARAMDESC PARAMDESC;

/* 110 */
#pragma pack(push, 8)
union tagELEMDESC::$7C8F4CED1424251743D09680A1A0B07D
{
  IDLDESC idldesc;
  PARAMDESC paramdesc;
};
#pragma pack(pop)

/* 109 */
#pragma pack(push, 8)
struct tagELEMDESC
{
  TYPEDESC tdesc;
  #pragma pack(push, 8)
  union
  {
    IDLDESC idldesc;
    PARAMDESC paramdesc;
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 107 */
#pragma pack(push, 8)
struct tagFUNCDESC
{
  MEMBERID memid;
  SCODE *lprgscode;
  ELEMDESC *lprgelemdescParam;
  FUNCKIND funckind;
  INVOKEKIND invkind;
  CALLCONV callconv;
  SHORT cParams;
  SHORT cParamsOpt;
  SHORT oVft;
  SHORT cScodes;
  ELEMDESC elemdescFunc;
  WORD wFuncFlags;
};
#pragma pack(pop)

/* 123 */
#pragma pack(push, 8)
union tagVARDESC::$E6274BD6A7149C9CC2413444FF769F0B
{
  ULONG oInst;
  VARIANT *lpvarValue;
};
#pragma pack(pop)

/* 125 */
enum tagVARKIND
{
  VAR_PERINSTANCE = 0x0,
  VAR_STATIC = 0x1,
  VAR_CONST = 0x2,
  VAR_DISPATCH = 0x3,
};

/* 124 */
typedef enum tagVARKIND VARKIND;

/* 122 */
#pragma pack(push, 8)
struct tagVARDESC
{
  MEMBERID memid;
  LPOLESTR lpstrSchema;
  #pragma pack(push, 8)
  union
  {
    ULONG oInst;
    VARIANT *lpvarValue;
  };
  #pragma pack(pop)
  ELEMDESC elemdescVar;
  WORD wVarFlags;
  VARKIND varkind;
};
#pragma pack(pop)

/* 131 */
#pragma pack(push, 8)
struct ITypeLib
{
  struct ITypeLibVtbl *lpVtbl;
};
#pragma pack(pop)

/* 93 */
#pragma pack(push, 8)
struct tagARRAYDESC
{
  TYPEDESC tdescElem;
  USHORT cDims;
  SAFEARRAYBOUND rgbounds[1];
};
#pragma pack(pop)

/* 103 */
enum tagDESCKIND
{
  DESCKIND_NONE = 0x0,
  DESCKIND_FUNCDESC = 0x1,
  DESCKIND_VARDESC = 0x2,
  DESCKIND_TYPECOMP = 0x3,
  DESCKIND_IMPLICITAPPOBJ = 0x4,
  DESCKIND_MAX = 0x5,
};

/* 102 */
typedef enum tagDESCKIND DESCKIND;

/* 104 */
typedef union tagBINDPTR BINDPTR;

/* 101 */
#pragma pack(push, 8)
struct ITypeCompVtbl
{
  HRESULT (__stdcall *QueryInterface)(ITypeComp *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(ITypeComp *This);
  ULONG (__stdcall *Release)(ITypeComp *This);
  HRESULT (__stdcall *Bind)(ITypeComp *This, LPOLESTR szName, ULONG lHashVal, WORD wFlags, ITypeInfo **ppTInfo, DESCKIND *pDescKind, BINDPTR *pBindPtr);
  HRESULT (__stdcall *BindType)(ITypeComp *This, LPOLESTR szName, ULONG lHashVal, ITypeInfo **ppTInfo, ITypeComp **ppTComp);
};
#pragma pack(pop)

/* 114 */
#pragma pack(push, 8)
struct tagPARAMDESCEX
{
  ULONG cBytes;
  VARIANTARG varDefaultValue;
};
#pragma pack(pop)

/* 133 */
typedef struct tagTLIBATTR TLIBATTR;

/* 132 */
#pragma pack(push, 8)
struct ITypeLibVtbl
{
  HRESULT (__stdcall *QueryInterface)(ITypeLib *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(ITypeLib *This);
  ULONG (__stdcall *Release)(ITypeLib *This);
  UINT (__stdcall *GetTypeInfoCount)(ITypeLib *This);
  HRESULT (__stdcall *GetTypeInfo)(ITypeLib *This, UINT index, ITypeInfo **ppTInfo);
  HRESULT (__stdcall *GetTypeInfoType)(ITypeLib *This, UINT index, TYPEKIND *pTKind);
  HRESULT (__stdcall *GetTypeInfoOfGuid)(ITypeLib *This, const GUID *const guid, ITypeInfo **ppTinfo);
  HRESULT (__stdcall *GetLibAttr)(ITypeLib *This, TLIBATTR **ppTLibAttr);
  HRESULT (__stdcall *GetTypeComp)(ITypeLib *This, ITypeComp **ppTComp);
  HRESULT (__stdcall *GetDocumentation)(ITypeLib *This, INT index, BSTR *pBstrName, BSTR *pBstrDocString, DWORD *pdwHelpContext, BSTR *pBstrHelpFile);
  HRESULT (__stdcall *IsName)(ITypeLib *This, LPOLESTR szNameBuf, ULONG lHashVal, BOOL *pfName);
  HRESULT (__stdcall *FindName)(ITypeLib *This, LPOLESTR szNameBuf, ULONG lHashVal, ITypeInfo **ppTInfo, MEMBERID *rgMemId, USHORT *pcFound);
  void (__stdcall *ReleaseTLibAttr)(ITypeLib *This, TLIBATTR *pTLibAttr);
};
#pragma pack(pop)

/* 105 */
#pragma pack(push, 8)
union tagBINDPTR
{
  FUNCDESC *lpfuncdesc;
  VARDESC *lpvardesc;
  ITypeComp *lptcomp;
};
#pragma pack(pop)

/* 136 */
enum tagSYSKIND
{
  SYS_WIN16 = 0x0,
  SYS_WIN32 = 0x1,
  SYS_MAC = 0x2,
  SYS_WIN64 = 0x3,
};

/* 135 */
typedef enum tagSYSKIND SYSKIND;

/* 134 */
#pragma pack(push, 8)
struct tagTLIBATTR
{
  GUID guid;
  LCID lcid;
  SYSKIND syskind;
  WORD wMajorVerNum;
  WORD wMinorVerNum;
  WORD wLibFlags;
};
#pragma pack(pop)

/* 152 */
typedef unsigned int UINT_PTR;

/* 151 */
typedef UINT_PTR WPARAM;

/* 153 */
typedef const CHAR *LPCCH;

/* 154 */
typedef char *va_list;

/* 156 */
typedef const struct _s_ThrowInfo ThrowInfo;

/* 155 */
typedef ThrowInfo _ThrowInfo;

/* 158 */
typedef void (__cdecl *PMFN)(void *);

/* 159 */
typedef const struct _s_CatchableTypeArray CatchableTypeArray;

/* 157 */
#pragma pack(push, 4)
struct _s_ThrowInfo
{
  unsigned int attributes;
  PMFN pmfnUnwind;
  int (__cdecl *pForwardCompat)();
  CatchableTypeArray *pCatchableTypeArray;
};
#pragma pack(pop)

/* 161 */
typedef const struct _s_CatchableType CatchableType;

/* 160 */
#pragma pack(push, 4)
struct _s_CatchableTypeArray
{
  int nCatchableTypes;
  CatchableType *arrayOfCatchableTypes[];
};
#pragma pack(pop)

/* 164 */
#pragma pack(push, 4)
struct PMD
{
  int mdisp;
  int pdisp;
  int vdisp;
};
#pragma pack(pop)

/* 162 */
#pragma pack(push, 4)
struct _s_CatchableType
{
  unsigned int properties;
  TypeDescriptor *pType;
  PMD thisDisplacement;
  int sizeOrOffset;
  PMFN copyFunction;
};
#pragma pack(pop)

/* 163 */
#pragma pack(push, 4)
struct TypeDescriptor
{
  unsigned int hash;
  void *spare;
  char name[];
};
#pragma pack(pop)

/* 165 */
struct tagRECT
{
  LONG left;
  LONG top;
  LONG right;
  LONG bottom;
};

/* 166 */
typedef struct _IP_ADAPTER_ADDRESSES_LH IP_ADAPTER_ADDRESSES_LH;

/* 171 */
typedef ULONG NET_IFINDEX;

/* 170 */
typedef NET_IFINDEX IF_INDEX;

/* 169 */
struct _IP_ADAPTER_ADDRESSES_LH::$88EAB68B38CC03D4ADFF2CEE83F7F421::$540D896092981D96F2B14DC684EC72A2
{
  ULONG Length;
  IF_INDEX IfIndex;
};

/* 168 */
union _IP_ADAPTER_ADDRESSES_LH::$88EAB68B38CC03D4ADFF2CEE83F7F421
{
  ULONGLONG Alignment;
  struct
  {
    ULONG Length;
    IF_INDEX IfIndex;
  };
};

/* 172 */
typedef CHAR *PCHAR;

/* 173 */
typedef struct _IP_ADAPTER_UNICAST_ADDRESS_LH *PIP_ADAPTER_UNICAST_ADDRESS_LH;

/* 192 */
typedef struct _IP_ADAPTER_ANYCAST_ADDRESS_XP *PIP_ADAPTER_ANYCAST_ADDRESS_XP;

/* 196 */
typedef struct _IP_ADAPTER_MULTICAST_ADDRESS_XP *PIP_ADAPTER_MULTICAST_ADDRESS_XP;

/* 200 */
typedef struct _IP_ADAPTER_DNS_SERVER_ADDRESS_XP *PIP_ADAPTER_DNS_SERVER_ADDRESS_XP;

/* 204 */
typedef WCHAR *PWCHAR;

/* 206 */
struct _IP_ADAPTER_ADDRESSES_LH::$25CF9B0FF74BBFD763B030897BA4FF99::$E43178AF9457E50D9523A864F18E103E
{
  unsigned __int32 DdnsEnabled : 1;
  unsigned __int32 RegisterAdapterSuffix : 1;
  unsigned __int32 Dhcpv4Enabled : 1;
  unsigned __int32 ReceiveOnly : 1;
  unsigned __int32 NoMulticast : 1;
  unsigned __int32 Ipv6OtherStatefulConfig : 1;
  unsigned __int32 NetbiosOverTcpipEnabled : 1;
  unsigned __int32 Ipv4Enabled : 1;
  unsigned __int32 Ipv6Enabled : 1;
  unsigned __int32 Ipv6ManagedAddressConfigurationSupported : 1;
};

/* 205 */
union _IP_ADAPTER_ADDRESSES_LH::$25CF9B0FF74BBFD763B030897BA4FF99
{
  ULONG Flags;
  struct
  {
    unsigned __int32 DdnsEnabled : 1;
    unsigned __int32 RegisterAdapterSuffix : 1;
    unsigned __int32 Dhcpv4Enabled : 1;
    unsigned __int32 ReceiveOnly : 1;
    unsigned __int32 NoMulticast : 1;
    unsigned __int32 Ipv6OtherStatefulConfig : 1;
    unsigned __int32 NetbiosOverTcpipEnabled : 1;
    unsigned __int32 Ipv4Enabled : 1;
    unsigned __int32 Ipv6Enabled : 1;
    unsigned __int32 Ipv6ManagedAddressConfigurationSupported : 1;
  };
};

/* 207 */
typedef ULONG IFTYPE;

/* 209 */
enum $1D78DD8871C05E6FD7D3820402F49BC1
{
  IfOperStatusUp = 0x1,
  IfOperStatusDown = 0x2,
  IfOperStatusTesting = 0x3,
  IfOperStatusUnknown = 0x4,
  IfOperStatusDormant = 0x5,
  IfOperStatusNotPresent = 0x6,
  IfOperStatusLowerLayerDown = 0x7,
};

/* 208 */
typedef enum $1D78DD8871C05E6FD7D3820402F49BC1 IF_OPER_STATUS;

/* 210 */
typedef struct _IP_ADAPTER_PREFIX_XP *PIP_ADAPTER_PREFIX_XP;

/* 214 */
typedef unsigned __int64 ULONG64;

/* 215 */
typedef struct _IP_ADAPTER_WINS_SERVER_ADDRESS_LH *PIP_ADAPTER_WINS_SERVER_ADDRESS_LH;

/* 219 */
typedef struct _IP_ADAPTER_GATEWAY_ADDRESS_LH *PIP_ADAPTER_GATEWAY_ADDRESS_LH;

/* 227 */
struct _NET_LUID_LH::$0227A65EDE726BD8ABDBF310B0E65A75
{
  unsigned __int64 Reserved : 24;
  unsigned __int64 NetLuidIndex : 24;
  unsigned __int64 IfType : 16;
};

/* 226 */
union _NET_LUID_LH
{
  ULONG64 Value;
  struct _NET_LUID_LH::$0227A65EDE726BD8ABDBF310B0E65A75 Info;
};

/* 225 */
typedef union _NET_LUID_LH NET_LUID_LH;

/* 224 */
typedef NET_LUID_LH NET_LUID;

/* 223 */
typedef NET_LUID IF_LUID;

/* 179 */
typedef struct sockaddr *LPSOCKADDR;

/* 178 */
struct _SOCKET_ADDRESS
{
  LPSOCKADDR lpSockaddr;
  INT iSockaddrLength;
};

/* 177 */
typedef struct _SOCKET_ADDRESS SOCKET_ADDRESS;

/* 229 */
typedef unsigned int UINT32;

/* 228 */
typedef UINT32 NET_IF_COMPARTMENT_ID;

/* 230 */
typedef GUID NET_IF_NETWORK_GUID;

/* 232 */
enum _NET_IF_CONNECTION_TYPE
{
  NET_IF_CONNECTION_DEDICATED = 0x1,
  NET_IF_CONNECTION_PASSIVE = 0x2,
  NET_IF_CONNECTION_DEMAND = 0x3,
  NET_IF_CONNECTION_MAXIMUM = 0x4,
};

/* 231 */
typedef enum _NET_IF_CONNECTION_TYPE NET_IF_CONNECTION_TYPE;

/* 234 */
enum $E38CE7F1AC08E248910BE7D26668C82A
{
  TUNNEL_TYPE_NONE = 0x0,
  TUNNEL_TYPE_OTHER = 0x1,
  TUNNEL_TYPE_DIRECT = 0x2,
  TUNNEL_TYPE_6TO4 = 0xB,
  TUNNEL_TYPE_ISATAP = 0xD,
  TUNNEL_TYPE_TEREDO = 0xE,
  TUNNEL_TYPE_IPHTTPS = 0xF,
};

/* 233 */
typedef enum $E38CE7F1AC08E248910BE7D26668C82A TUNNEL_TYPE;

/* 235 */
typedef struct _IP_ADAPTER_DNS_SUFFIX *PIP_ADAPTER_DNS_SUFFIX;

/* 167 */
struct _IP_ADAPTER_ADDRESSES_LH
{
  union
  {
    ULONGLONG Alignment;
    struct
    {
      ULONG Length;
      IF_INDEX IfIndex;
    };
  };
  struct _IP_ADAPTER_ADDRESSES_LH *Next;
  PCHAR AdapterName;
  PIP_ADAPTER_UNICAST_ADDRESS_LH FirstUnicastAddress;
  PIP_ADAPTER_ANYCAST_ADDRESS_XP FirstAnycastAddress;
  PIP_ADAPTER_MULTICAST_ADDRESS_XP FirstMulticastAddress;
  PIP_ADAPTER_DNS_SERVER_ADDRESS_XP FirstDnsServerAddress;
  PWCHAR DnsSuffix;
  PWCHAR Description;
  PWCHAR FriendlyName;
  BYTE PhysicalAddress[8];
  ULONG PhysicalAddressLength;
  union
  {
    ULONG Flags;
    struct
    {
      unsigned __int32 DdnsEnabled : 1;
      unsigned __int32 RegisterAdapterSuffix : 1;
      unsigned __int32 Dhcpv4Enabled : 1;
      unsigned __int32 ReceiveOnly : 1;
      unsigned __int32 NoMulticast : 1;
      unsigned __int32 Ipv6OtherStatefulConfig : 1;
      unsigned __int32 NetbiosOverTcpipEnabled : 1;
      unsigned __int32 Ipv4Enabled : 1;
      unsigned __int32 Ipv6Enabled : 1;
      unsigned __int32 Ipv6ManagedAddressConfigurationSupported : 1;
    };
  };
  ULONG Mtu;
  IFTYPE IfType;
  IF_OPER_STATUS OperStatus;
  IF_INDEX Ipv6IfIndex;
  ULONG ZoneIndices[16];
  PIP_ADAPTER_PREFIX_XP FirstPrefix;
  ULONG64 TransmitLinkSpeed;
  ULONG64 ReceiveLinkSpeed;
  PIP_ADAPTER_WINS_SERVER_ADDRESS_LH FirstWinsServerAddress;
  PIP_ADAPTER_GATEWAY_ADDRESS_LH FirstGatewayAddress;
  ULONG Ipv4Metric;
  ULONG Ipv6Metric;
  IF_LUID Luid;
  SOCKET_ADDRESS Dhcpv4Server;
  NET_IF_COMPARTMENT_ID CompartmentId;
  NET_IF_NETWORK_GUID NetworkGuid;
  NET_IF_CONNECTION_TYPE ConnectionType;
  TUNNEL_TYPE TunnelType;
  SOCKET_ADDRESS Dhcpv6Server;
  BYTE Dhcpv6ClientDuid[130];
  ULONG Dhcpv6ClientDuidLength;
  ULONG Dhcpv6Iaid;
  PIP_ADAPTER_DNS_SUFFIX FirstDnsSuffix;
};

/* 176 */
struct _IP_ADAPTER_UNICAST_ADDRESS_LH::$E412F09F4EF1DCB2A353111A4C8EAC81::$558C11AAB270A8DE5636A48AC52A55A4
{
  ULONG Length;
  DWORD Flags;
};

/* 175 */
union _IP_ADAPTER_UNICAST_ADDRESS_LH::$E412F09F4EF1DCB2A353111A4C8EAC81
{
  ULONGLONG Alignment;
  struct
  {
    ULONG Length;
    DWORD Flags;
  };
};

/* 184 */
enum $81C96E3F196AC83D02B4522B31857D28
{
  IpPrefixOriginOther = 0x0,
  IpPrefixOriginManual = 0x1,
  IpPrefixOriginWellKnown = 0x2,
  IpPrefixOriginDhcp = 0x3,
  IpPrefixOriginRouterAdvertisement = 0x4,
  IpPrefixOriginUnchanged = 0x10,
};

/* 183 */
typedef enum $81C96E3F196AC83D02B4522B31857D28 NL_PREFIX_ORIGIN;

/* 182 */
typedef NL_PREFIX_ORIGIN IP_PREFIX_ORIGIN;

/* 187 */
enum $4ADD18C59427D2D4505C2F6B781D5A2B
{
  NlsoOther = 0x0,
  NlsoManual = 0x1,
  NlsoWellKnown = 0x2,
  NlsoDhcp = 0x3,
  NlsoLinkLayerAddress = 0x4,
  NlsoRandom = 0x5,
  IpSuffixOriginOther = 0x0,
  IpSuffixOriginManual = 0x1,
  IpSuffixOriginWellKnown = 0x2,
  IpSuffixOriginDhcp = 0x3,
  IpSuffixOriginLinkLayerAddress = 0x4,
  IpSuffixOriginRandom = 0x5,
  IpSuffixOriginUnchanged = 0x10,
};

/* 186 */
typedef enum $4ADD18C59427D2D4505C2F6B781D5A2B NL_SUFFIX_ORIGIN;

/* 185 */
typedef NL_SUFFIX_ORIGIN IP_SUFFIX_ORIGIN;

/* 190 */
enum $06D1ED250FD368380D92731A8809DBAC
{
  NldsInvalid = 0x0,
  NldsTentative = 0x1,
  NldsDuplicate = 0x2,
  NldsDeprecated = 0x3,
  NldsPreferred = 0x4,
  IpDadStateInvalid = 0x0,
  IpDadStateTentative = 0x1,
  IpDadStateDuplicate = 0x2,
  IpDadStateDeprecated = 0x3,
  IpDadStatePreferred = 0x4,
};

/* 189 */
typedef enum $06D1ED250FD368380D92731A8809DBAC NL_DAD_STATE;

/* 188 */
typedef NL_DAD_STATE IP_DAD_STATE;

/* 191 */
typedef unsigned __int8 UINT8;

/* 174 */
struct _IP_ADAPTER_UNICAST_ADDRESS_LH
{
  union
  {
    ULONGLONG Alignment;
    struct
    {
      ULONG Length;
      DWORD Flags;
    };
  };
  struct _IP_ADAPTER_UNICAST_ADDRESS_LH *Next;
  SOCKET_ADDRESS Address;
  IP_PREFIX_ORIGIN PrefixOrigin;
  IP_SUFFIX_ORIGIN SuffixOrigin;
  IP_DAD_STATE DadState;
  ULONG ValidLifetime;
  ULONG PreferredLifetime;
  ULONG LeaseLifetime;
  UINT8 OnLinkPrefixLength;
};

/* 195 */
struct _IP_ADAPTER_ANYCAST_ADDRESS_XP::$27D98D245193571B98223D43E8FDA74A::$558C11AAB270A8DE5636A48AC52A55A4
{
  ULONG Length;
  DWORD Flags;
};

/* 194 */
union _IP_ADAPTER_ANYCAST_ADDRESS_XP::$27D98D245193571B98223D43E8FDA74A
{
  ULONGLONG Alignment;
  struct
  {
    ULONG Length;
    DWORD Flags;
  };
};

/* 193 */
struct _IP_ADAPTER_ANYCAST_ADDRESS_XP
{
  union
  {
    ULONGLONG Alignment;
    struct
    {
      ULONG Length;
      DWORD Flags;
    };
  };
  struct _IP_ADAPTER_ANYCAST_ADDRESS_XP *Next;
  SOCKET_ADDRESS Address;
};

/* 199 */
struct _IP_ADAPTER_MULTICAST_ADDRESS_XP::$C661A151FC55CDAC9C76B7690C297B03::$558C11AAB270A8DE5636A48AC52A55A4
{
  ULONG Length;
  DWORD Flags;
};

/* 198 */
union _IP_ADAPTER_MULTICAST_ADDRESS_XP::$C661A151FC55CDAC9C76B7690C297B03
{
  ULONGLONG Alignment;
  struct
  {
    ULONG Length;
    DWORD Flags;
  };
};

/* 197 */
struct _IP_ADAPTER_MULTICAST_ADDRESS_XP
{
  union
  {
    ULONGLONG Alignment;
    struct
    {
      ULONG Length;
      DWORD Flags;
    };
  };
  struct _IP_ADAPTER_MULTICAST_ADDRESS_XP *Next;
  SOCKET_ADDRESS Address;
};

/* 203 */
struct _IP_ADAPTER_DNS_SERVER_ADDRESS_XP::$C726E6BF6F48850843A5B30ADC20782D::$F985BF779D0F5FE11994F28A81731018
{
  ULONG Length;
  DWORD Reserved;
};

/* 202 */
union _IP_ADAPTER_DNS_SERVER_ADDRESS_XP::$C726E6BF6F48850843A5B30ADC20782D
{
  ULONGLONG Alignment;
  struct
  {
    ULONG Length;
    DWORD Reserved;
  };
};

/* 201 */
struct _IP_ADAPTER_DNS_SERVER_ADDRESS_XP
{
  union
  {
    ULONGLONG Alignment;
    struct
    {
      ULONG Length;
      DWORD Reserved;
    };
  };
  struct _IP_ADAPTER_DNS_SERVER_ADDRESS_XP *Next;
  SOCKET_ADDRESS Address;
};

/* 213 */
struct _IP_ADAPTER_PREFIX_XP::$062DE21AAEE92240DFF2100A002A9516::$558C11AAB270A8DE5636A48AC52A55A4
{
  ULONG Length;
  DWORD Flags;
};

/* 212 */
union _IP_ADAPTER_PREFIX_XP::$062DE21AAEE92240DFF2100A002A9516
{
  ULONGLONG Alignment;
  struct
  {
    ULONG Length;
    DWORD Flags;
  };
};

/* 211 */
struct _IP_ADAPTER_PREFIX_XP
{
  union
  {
    ULONGLONG Alignment;
    struct
    {
      ULONG Length;
      DWORD Flags;
    };
  };
  struct _IP_ADAPTER_PREFIX_XP *Next;
  SOCKET_ADDRESS Address;
  ULONG PrefixLength;
};

/* 218 */
struct _IP_ADAPTER_WINS_SERVER_ADDRESS_LH::$ED1413B78AFF918A573A0A81B51AB7FA::$F985BF779D0F5FE11994F28A81731018
{
  ULONG Length;
  DWORD Reserved;
};

/* 217 */
union _IP_ADAPTER_WINS_SERVER_ADDRESS_LH::$ED1413B78AFF918A573A0A81B51AB7FA
{
  ULONGLONG Alignment;
  struct
  {
    ULONG Length;
    DWORD Reserved;
  };
};

/* 216 */
struct _IP_ADAPTER_WINS_SERVER_ADDRESS_LH
{
  union
  {
    ULONGLONG Alignment;
    struct
    {
      ULONG Length;
      DWORD Reserved;
    };
  };
  struct _IP_ADAPTER_WINS_SERVER_ADDRESS_LH *Next;
  SOCKET_ADDRESS Address;
};

/* 222 */
struct _IP_ADAPTER_GATEWAY_ADDRESS_LH::$4DEA9AA2BE4A87A26E25AF13B4F5640E::$F985BF779D0F5FE11994F28A81731018
{
  ULONG Length;
  DWORD Reserved;
};

/* 221 */
union _IP_ADAPTER_GATEWAY_ADDRESS_LH::$4DEA9AA2BE4A87A26E25AF13B4F5640E
{
  ULONGLONG Alignment;
  struct
  {
    ULONG Length;
    DWORD Reserved;
  };
};

/* 220 */
struct _IP_ADAPTER_GATEWAY_ADDRESS_LH
{
  union
  {
    ULONGLONG Alignment;
    struct
    {
      ULONG Length;
      DWORD Reserved;
    };
  };
  struct _IP_ADAPTER_GATEWAY_ADDRESS_LH *Next;
  SOCKET_ADDRESS Address;
};

/* 181 */
typedef USHORT ADDRESS_FAMILY;

/* 180 */
struct sockaddr
{
  ADDRESS_FAMILY sa_family;
  CHAR sa_data[14];
};

/* 236 */
struct _IP_ADAPTER_DNS_SUFFIX
{
  struct _IP_ADAPTER_DNS_SUFFIX *Next;
  WCHAR String[256];
};

/* 238 */
typedef unsigned int u_int;

/* 239 */
typedef UINT_PTR SOCKET;

/* 237 */
struct fd_set
{
  u_int fd_count;
  SOCKET fd_array[64];
};

/* 240 */
struct timeval
{
  int tv_sec;
  int tv_usec;
};

/* 241 */
typedef void (__cdecl *_PVFV)();

/* 242 */
#pragma pack(push, 8)
struct _onexit_table_t
{
  _PVFV *_first;
  _PVFV *_last;
  _PVFV *_end;
};
#pragma pack(pop)

/* 245 */
typedef struct _EXCEPTION_RECORD EXCEPTION_RECORD;

/* 244 */
typedef EXCEPTION_RECORD *PEXCEPTION_RECORD;

/* 248 */
typedef struct _CONTEXT CONTEXT;

/* 247 */
typedef CONTEXT *PCONTEXT;

/* 243 */
struct _EXCEPTION_POINTERS
{
  PEXCEPTION_RECORD ExceptionRecord;
  PCONTEXT ContextRecord;
};

/* 246 */
struct _EXCEPTION_RECORD
{
  DWORD ExceptionCode;
  DWORD ExceptionFlags;
  struct _EXCEPTION_RECORD *ExceptionRecord;
  PVOID ExceptionAddress;
  DWORD NumberParameters;
  ULONG_PTR ExceptionInformation[15];
};

/* 251 */
struct _FLOATING_SAVE_AREA
{
  DWORD ControlWord;
  DWORD StatusWord;
  DWORD TagWord;
  DWORD ErrorOffset;
  DWORD ErrorSelector;
  DWORD DataOffset;
  DWORD DataSelector;
  BYTE RegisterArea[80];
  DWORD Spare0;
};

/* 250 */
typedef struct _FLOATING_SAVE_AREA FLOATING_SAVE_AREA;

/* 249 */
#pragma pack(push, 4)
struct _CONTEXT
{
  DWORD ContextFlags;
  DWORD Dr0;
  DWORD Dr1;
  DWORD Dr2;
  DWORD Dr3;
  DWORD Dr6;
  DWORD Dr7;
  FLOATING_SAVE_AREA FloatSave;
  DWORD SegGs;
  DWORD SegFs;
  DWORD SegEs;
  DWORD SegDs;
  DWORD Edi;
  DWORD Esi;
  DWORD Ebx;
  DWORD Edx;
  DWORD Ecx;
  DWORD Eax;
  DWORD Ebp;
  DWORD Eip;
  DWORD SegCs;
  DWORD EFlags;
  DWORD Esp;
  DWORD SegSs;
  BYTE ExtendedRegisters[512];
};
#pragma pack(pop)

/* 253 */
typedef WCHAR *LPWSTR;

/* 252 */
struct _STARTUPINFOW
{
  DWORD cb;
  LPWSTR lpReserved;
  LPWSTR lpDesktop;
  LPWSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};

/* 254 */
typedef union _LARGE_INTEGER LARGE_INTEGER;

/* 256 */
struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E
{
  DWORD LowPart;
  LONG HighPart;
};

/* 255 */
union _LARGE_INTEGER
{
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  };
  struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E u;
  LONGLONG QuadPart;
};

/* 257 */
typedef const WCHAR *LPCWCH;

/* 258 */
typedef IP_ADAPTER_ADDRESSES_LH *PIP_ADAPTER_ADDRESSES;

/* 259 */
typedef ULONG *PULONG;

/* 260 */
typedef int (__cdecl *_onexit_t)();

/* 261 */
typedef void (__stdcall *_tls_callback_type)(void *, unsigned int, void *);

/* 265 */
struct _SINGLE_LIST_ENTRY
{
  struct _SINGLE_LIST_ENTRY *Next;
};

/* 264 */
typedef struct _SINGLE_LIST_ENTRY SLIST_ENTRY;

/* 263 */
struct _SLIST_HEADER::$04C3B4B3818F1694974352AE64BF5082
{
  SLIST_ENTRY Next;
  WORD Depth;
  WORD CpuId;
};

/* 262 */
union _SLIST_HEADER
{
  ULONGLONG Alignment;
  struct
  {
    SLIST_ENTRY Next;
    WORD Depth;
    WORD CpuId;
  };
};

/* 266 */
enum _crt_argv_mode
{
  _crt_argv_no_arguments = 0x0,
  _crt_argv_unexpanded_arguments = 0x1,
  _crt_argv_expanded_arguments = 0x2,
};

/* 267 */
enum _crt_app_type
{
  _crt_unknown_app = 0x0,
  _crt_console_app = 0x1,
  _crt_gui_app = 0x2,
};

/* 268 */
typedef int (__cdecl *_UserMathErrorFunctionPointer)(struct _exception *);

/* 269 */
#pragma pack(push, 8)
struct _exception
{
  int type;
  char *name;
  double arg1;
  double arg2;
  double retval;
};
#pragma pack(pop)

/* 270 */
typedef __int64 fpos_t;

/* 271 */
struct CWinApp;

/* 272 */
struct CWnd;

/* 273 */
struct CListCtrl;

/* 274 */
struct CStdioFile;

/* 275 */
struct CSyncObject;

/* 276 */
struct CCmdTarget;

/* 277 */
struct CHtmlEditView;

/* 278 */
struct CHtmlView;

/* 279 */
struct CMFCMenuBar;

/* 280 */
struct CFrameWnd;

/* 281 */
struct CDialog;

/* 282 */
struct CWinThread;

/* 283 */
struct CCommandLineInfo;

/* 284 */
struct CMultiPaneFrameWnd;

/* 285 */
struct CException;

/* 286 */
struct CFileException;

/* 287 */
struct CFile;

/* 288 */
struct CPaintDC;

/* 289 */
typedef struct HMENU__ *HMENU;

/* 290 */
struct HMENU__
{
  int unused;
};

/* 291 */
typedef struct HWND__ *HWND;

/* 292 */
struct HWND__
{
  int unused;
};

/* 293 */
struct COleDocIPFrameWndEx;

/* 294 */
struct COleServerItem;

/* 295 */
struct CVSListBoxBase;

/* 296 */
struct CStringList;

/* 297 */
struct ATL::CComCriticalSection;

/* 298 */
struct std::_Fac_node;

/* 299 */
struct std::_Fac_tidy_reg_t;

/* 300 */
struct CMDIClientAreaWnd;

/* 301 */
struct CMFCRibbonInfo::XID;

